x-labels: &network
  networks:
    - iset

services:
  files:
    image: orchestrator-local:latest
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: orchestrator-local
    hostname: orchestrator-local
    restart: always
    env_file: .env
    volumes:
        - ./backend:/iset:rw
    ports:
      - 8082:80
      - 5680:5680
    command: 
      [
        'bash',
        '-c',
        'python -m debugpy --wait-for-client --listen 0.0.0.0:5680 -m uvicorn app.src.main:app --host 0.0.0.0 --port 80 --reload'
      ]
    depends_on:
      - rabbitmq
    <<: *network

  rabbitmq:
    image: bitnami/rabbitmq:4.1.0-debian-12-r1
    container_name: rabbitmq-local
    hostname: rabbitmq-local
    restart: always
    ports:
      - "5672:5672"   # AMQP порт
      - "15672:15672" # Web UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
      # - RABBITMQ_LOAD_DEFINITIONS=yes
      # - RABBITMQ_DEFINITIONS_FILE=/etc/rabbitmq/load_definition.json
    # volumes:
    #   - ./backend/app/configs/load_definition.json:/etc/rabbitmq/load_definition.json
    <<: *network


networks:
  iset:
    name: iset-local
